classpass/blueprints/common/routes.py
from flask import flash, redirect, render_template, request, session, url_for, Blueprint, abort
from flask_login import login_user, current_user, logout_user, login_required

from ...database.models import Users, Cards
from ...extensions import db, bcrypt
from .forms import Register_form, Login_form
from ...user_utils import url_has_allowed_host_and_scheme

# Blueprint Variable
common_bp = Blueprint("common", __name__, url_prefix="/common")


@common_bp.after_request
def after_request(response):
    """Ensure responses aren't cached"""
    response.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
    response.headers["Expires"] = 0
    response.headers["Pragma"] = "no-cache"
    return response


# Routes
@common_bp.route("/")
def index():
    return redirect(url_for("common.login"))


@common_bp.route("/login", methods=["GET", "POST"])
def login():

    # Get form with WTForms
    form = Login_form(request.form)

    if request.method == "POST" and form.validate_on_submit():
        # Get data from form
        username = form.username.data
        password = form.password.data

        user_record = Users.query.filter_by(username=username).first()
        if not user_record or not bcrypt.check_password_hash(user_record.password, password):
            flash("Invalid Username or password!", "danger")
            return redirect(url_for('login'))

        login_user(user_record)

        next = request.args.get('next')

        if not next:
            next = url_for("auth.index")
        else:
            if not url_has_allowed_host_and_scheme(next, request.host):
                return abort(400)

        if current_user.is_authenticated:
            session["user_type"] = user_record.type
            session["user_card_id"] = user_record.card_id
            return redirect(next)

    return render_template("login.html", form=form)


@common_bp.route('/logout')
@login_required
def logout():

    # Check if the user is logged in
    if not current_user.is_authenticated:
        return redirect(url_for("common.login", next=url_for("common.login")))

    session.clear()
    logout_user()

    return redirect(url_for("common.index"))


@common_bp.route('/register', methods=['GET', 'POST'])
def register():

    # Get form with WTForms
    form = Register_form(request.form)

    if request.method == 'POST' and form.validate_on_submit():

        # Get data from form
        username = form.username.data
        email = form.email.data
        password = form.password.data
        user_type = form.type.data

        # Get data from Cards
        card_record = Cards.query.filter_by(uid=form.card.data).first()
        card_uid = card_record.id

        # Update 'has_user'
        card_record.has_user = 1

        # Create a new user
        new_user = Users(username=username, email=email, password=bcrypt.generate_password_hash(
            password), type=user_type, card_id=card_uid)
        db.session.add(new_user)
        db.session.commit()

        return redirect(url_for('common.login'))

    return render_template('register.html', form=form)

classpass/blueprints/graphs/routes.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user

# Blueprint Variable
graphs_bp = Blueprint("graphs", __name__, url_prefix="/graphs")


@graphs_bp.after_request
def after_request(response):
    """Ensure responses aren't cached"""
    response.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
    response.headers["Expires"] = 0
    response.headers["Pragma"] = "no-cache"
    return response


# Routes
@graphs_bp.route("/")
@login_required
def graph():

    # Check if the user is logged in
    if not current_user.is_authenticated:
        return redirect(url_for("common.login", next=url_for("common.login")))

    # Chart.js
    return render_template("graphs.html")

classpass/templates/graphs.html
{% extends "layout.html" %}

{% block title %}
System's Overview
{% endblock %}

{% block javascript %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
<script src="/static/js/graphs.js"></script>
{% endblock %}

{% block buttons %}
<div class="cl-row-bottom">
  <button class="btn-left" type="button" value="1">Graph 01</button>
  <button class="btn-left" type="button" value="2">Graph 02</button>
  <button class="btn-left" type="button" value="3">Graph 03</button>
  <button class="btn-left" type="button" value="4">Graph 04</button>
</div>
{% endblock %}

{% block body %}
<div class="column-right">
  <div class="column">
    <div class="chart-container">
      <canvas id="chart" height="600px" width="600px"></canvas>
    </div>
  </div>
  <div class="column">
    <div class="select-container" style="display: none;">
      <label for="argsSelect">Select a Place:</label>
      <select id="argsSelect" name="select">
      </select>
    </div>
  </div>
</div>

{% endblock %}

classpass/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Managing System {% block title %}{% endblock %}</title>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/static/css/styles.css">
  {% block javascript %}{% endblock %}
</head>

<body>

  <div class="row">
    <div class="column-left">
      <div class="cl-row-top">
        <nav>
          <ul>
            <li><a href="{{url_for('auth.index')}}">Home</a></li>
            <li><a href="/tables">Tables</a></li>
            <li><a href="/graphs">Graphs</a></li>
            <li><a href="{{url_for('common.logout')}}">Logout</a></li>
          </ul>
        </nav>
      </div>
      {% block buttons %}

      {% endblock %}
    </div>

    {% block body %}

    {% endblock %}

  </div>
</body>

</html>

classpass/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/static/css/login.css">
</head>

<body>
  <div class="container">
    <div class="login-header">
      <h3>Login</h3>
      <h4>Welcome back!</h4>
    </div>
    <form class="login-form" action="{{url_for('common.login')}}" method="post">
      {{ form.csrf_token }}
      <div class="login-username">
        {{ form.username.label }}
        {{ form.username(placeholder="Username") }}
        {% if form.username.errors %}
        <div class="form-error">
          <ul>
            {% for error in form.username.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
      </div>
      <div class="login-password">
        {{ form.password.label }}
        {{ form.password(placeholder="Password") }}
        {% if form.password.errors %}
        <div class="form-error">
          <ul>
            {% for error in form.password.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
      </div>
      <div class="login-button">
        <button class="login" type="submit">LOGIN</button>
      </div>
    </form>
    <div class="login-footer">
      <p>New Here? <a href="{{url_for('common.register')}}">Create an account</a></p>
    </div>
  </div>
</body>

</html>

classpass/templates/overview.html
{% extends "layout.html" %}

{% block title %}Overview{% endblock %}

{% block javascript %}
<script type="text/javascript">var cardId = "{{ card_id }}";</script>
<script type="text/javascript" src="../static/js/overview.js"></script>
{% endblock %}

{% if acc_info %}
{% block buttons %}
<div class="user-data">
  {% for key, value in acc_info.items() %}
  <div class="user-items">
    <span class="h">{{ key }}:</span>
    <span class="t">{{ value }}</span>
  </div>
  {% endfor %}
</div>
{% endblock %}
{% endif %}

{% block body %}
<div class="column-right">

  <div class="row">
    <div class="main-header">
      <h1>Overview</h1>
      <h2>So, what this app is about?</h2>
      <p>This is an interface to make the data of a database more user-friedly to read. It displays tables and renders
        graphs for simple analyses.</p>

      <p>Currently it servers as a portal of data from a bigger system called 'classpass', that is a college's exercise.
        This exercise proposed to identify and create a technology system in the campus to solve any kind of problem
        and the idea 'classpass' was created as a security system to identify who is entering in the property of the
        college. The approach is to start using RFID Cards in every entrance and buildings and gradually turning the
        RFIDs into NFCs as the technology could be an stantard to every new phone.</p>

      <p>The work here was about architecting and developing the app that could display the data created from the
        system, but in this case, it was generated from 'populate.py'. As serving as a tool for the security, this app
        could help monitorate the flow of registers, see statics that could help improve the inner space of the college,
        as a reference of 'usage' of the space. For example, the college could see that, the course 'x' is the course
        that lesat use the library, so maybe it should ask the students the reasons for that or simply buying more books
        about the related topics.</p>
    </div>
  </div>

  <div id="registers"></div>

</div>
{% endblock %}

classpass/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Register</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/static/css/register.css">
</head>

<body>
  <div class="container">
    <div class="register-header">
      <h3>Register</h3>
      <h4>Welcome!</h4>
    </div>
    <form class="register-form" action="{{url_for('common.register')}}" method=post>
      {{ form.csrf_token }}
      <div class="register-type">
        {{ form.type.label }}
        {{ form.type }}
        {% if form.type.errors %}
        <div class="form-error">
          <ul>
            {% for error in form.type.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
      </div>
      <div class="register-card">
        {{ form.card.label }}
        {{ form.card(placeholder="Card Uid") }}
        {% if form.card.errors %}
        <div class="form-error">
          <ul>
            {% for error in form.card.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
      </div>
      <div class="register-username">
        {{ form.username.label }}
        {{ form.username(placeholder="Username") }}
        {% if form.username.errors %}
        <div class="form-error">
          <ul>
            {% for error in form.username.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
      </div>
      <div class="register-email">
        {{ form.email.label }}
        {{ form.email(placeholder="Email") }}
        {% if form.email.errors %}
        <div class="form-error">
          <ul>
            {% for error in form.email.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
      </div>
      <div class="register-password">
        {{ form.password.label }}
        {{ form.password(placeholder="Password") }}
        {% if form.password.errors %}
        <div class="form-error">
          <ul>
            {% for error in form.password.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
      </div>
      <div class="register-cfrm">
        {{ form.confirm.label }}
        {{ form.confirm(placeholder="Confirm Password") }}
        {% if form.confirm.errors %}
        <div class="form-error">
          <ul>
            {% for error in form.confirm.errors %}
            <li>{{ error }}</li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
      </div>
      <button class="register">Register</button>
    </form>
    <div class="register-footer">
      <p>Already have an account? <a href="{{url_for('common.login')}}">Login</a></p>
    </div>
  </div>
</body>

</html>

classpass/templates/tables.html
{% extends "layout.html" %}

{% block title %}
System's Overview
{% endblock %}

{% block javascript %}
<script src="../static/js/tables.js"></script>
{% endblock %}

{% if places %}
{% block buttons %}
<div class="cl-row-bottom">
  <button class="btn-left" id="place">All</button>
  {% for place in places %}
  <button class="btn-left" id="place">{{ place.description.title() }}</button>
  {% endfor %}
</div>
{% endblock %}
{% endif %}

{% block body %}
<div class="column-right">

  <div class="row">
    <div class="main-header">
      <h1>Tables</h1>
      <h2>Checkout your tables</h2>
    </div>
  </div>

  <div class="search">
    <div class="search-row-top">
      {{ form.card }}
    </div>

    <div class="search-row-bottom">
      {{ form.type }}
      {{ form.date }}
      {{ form.time }}
    </div>
  </div>

  <div id="search-results">

  </div>
</div>
{% endblock %}